services:

      backend:
        build: .
        ports:
          - "3000:3000"
          - "8080:8080"
        develop:
          watch:
            - action: sync
              path: .
              target: /app
        networks:
          - local
        
        volumes:
          - ./:/app

networks:
  local: